-- Migration 004: customer database — customers, guardians, and guardian_phones.
-- All PKs are TEXT (UUID v4) generated by the Main process via randomUUID().
-- Cascade deletes preserve referential integrity without orphaned rows.

CREATE TABLE IF NOT EXISTS customers (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  date_of_birth TEXT,           -- ISO-8601 date string (YYYY-MM-DD), nullable
  notes         TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_customers_name ON customers (name);

CREATE TABLE IF NOT EXISTS guardians (
  id          TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_guardians_customer_id ON guardians (customer_id);

CREATE TABLE IF NOT EXISTS guardian_phones (
  id         TEXT PRIMARY KEY,
  guardian_id TEXT NOT NULL REFERENCES guardians(id) ON DELETE CASCADE,
  phone      TEXT NOT NULL,
  label      TEXT,              -- e.g. 'celular', 'trabalho' — nullable
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_guardian_phones_guardian_id ON guardian_phones (guardian_id);
