/**
 * Zod validation schema for session check-in requests.
 * Shared between Main (IPC handler validation) and Renderer (form validation)
 * so the same rules are enforced at every layer — single source of truth.
 *
 * guardian_name and guardian_contact are stored on the session row.
 * The UUID and check_in_at timestamp are generated by the Main process;
 * the Renderer never sets them.
 */
import { z } from 'zod'

export const CheckInRequestSchema = z.object({
  child_name: z.string().min(1, 'Nome da crianca e obrigatorio'),
  guardian_name: z.string().min(1, 'Nome do responsavel e obrigatorio'),
  /** Optional — phone / WhatsApp. */
  guardian_contact: z.string().optional(),
  tariff_id: z.number().int().positive('Selecione uma tarifa valida'),
  /** Optional — UUID of an existing customer record. */
  customer_id: z.string().uuid().optional(),
})

export type CheckInRequestDto = z.infer<typeof CheckInRequestSchema>
